### ISSUE TITLE
0.5 release doesn't work on my TP-t480s  as  0.4 release ！！

### ISSUE THREAD

**Issue by eric2877** [VoodooSMBus/VoodooRMI#27]
as the title , my hackintosh 10.14.6 can work with 0.4 release, bug 0.5 can't drive the stuff,  unfortunately the commond "log show --last boot | grep -i voodoo > ~/Desktop/RMILog.txt" give me nothing , maybe I should use debug one ,  I will push the log to this issue this  night.

by pass
my device is Elan touchpad

**Comment by 1Revenger1** [comment]
For Elan trackpads, just use the VoodooSMBus kext. VoodooRMI is only for Synaptic trackpads. VoodooSMBus for now has baked in Elans support, but I took it out for the 0.5 release since we are working on stuff internally and causing issues with the Synaptic trackpads at time.

You can find the latest release of VoodooSMBus in the VoodooSMBus repo within this org.
