### ISSUE TITLE
Readme.md unclear

### ISSUE THREAD

**Issue by senolfeldmann** [VoodooSMBus/VoodooRMI#93]
The readme says the following:
"Disable VoodooPS2Trackpad, VoodooPS2Mouse, and if applicable, VoodooInput from within the PS2 kext"
Do you mean that these kexts should be disabled in OC's config.plist, or can they also be enabled in said config.plist but be in a disabled state via the VoodooPS2Controller kext itself?

This confuses me because the changelog of release 1.3 says (for SMBus):"Requires Acidanthera's VoodooPS2 2.2.0 with VoodooPS2Trackpad injected/enabled for this fix to work!"

I would be grateful for a clarification. Thanks!

**Comment by 1Revenger1** [comment]
Oops, I guess I probably forgot to change some stuff. When I say enable/disable, I generally mean setting "Enabled" in your config.plist for that particular kext to true/false.

You can keep VoodooPS2Trackpad enabled, though it is not a strict requirement. If you enable it, it allows the trackpad to be reset fully and can fix some odd behaviour on HP laptops especially. I'd recommend leaving it in.

I haven't tested leaving VoodooPS2Mouse enabled, might be fine since it would probe and then not start up since VoodooPS2TrackpadSynaptics has a higher probe score? I leave it disabled personally on my device - but I can test and update the readme.

You do want VoodooInput disabled from VoodooPS2 since that is a duplicate kext and VoodooRMI provides its own VoodooInput.

Thanks for catching that error!
