### ISSUE TITLE
Thinkpad E590 Intermittent issues

### ISSUE THREAD

**Issue by Someone52** [VoodooSMBus/VoodooRMI#96]
Running latest builds:

Board id: 0xd8f
Product id: 0x223

SMBUS, available: F01, F03, F12, F3A
Lenovo Thinkpad E590.

VoodooPS2SynapticsTouchPad: Tried with both doHardwareReset() and without (not loading PS2Trackpad)
No errors in the logs, SMBus driver seems to be attaching just fine either

Issue:

The trackpad either works great and without issues or quite poorly, this changes at random every reboot, i'd say there is around 50% chance it will boot to a working state.
When it works poorly, it seems to not register some touch gestures, especially clicking/tapping ones. 
If it boots into the 'good' state, it stays in such until next boot without a problem.

**Comment by 1Revenger1** [comment]
What are you using for your battery kext? I've seen sometimes where ACPIBatteryManager can cause issues due to reading _STA everytime it reads the battery information.

If it's not that, I honestly have no clue and you'll likely need to research it yourself. Would help if you could provide a log but I don't think there is a lot I can do currently.
